# <font color='blue'>Normalização e Padronização</font>

In [6]:
# Versão da Linguagem Python
from platform import python_version
print('Python Version:', python_version())

# Verificando as versões dos pacotes instalados
pandasVersion = !pip show pandas
matplotlibVersion = !pip show matplotlib
sklearnVersion = !pip show scikit-learn
print('Pandas', pandasVersion[1])
print("Matplotlib", matplotlibVersion[1])
print("Sklearn", sklearnVersion[1])

Python Version: 3.8.5
Pandas Version: 1.5.1
Matplotlib Version: 3.5.3
Plotly Version: 5.3.1
Sklearn Version: 1.1.2

## Normalização
<details>
    <summary>
        <a class="btnfire small stroke"><em class="fas fa-chevron-circle-down"></em>&nbsp;&nbsp;Clique para mais detalhes</a>
    </summary>
    <br>

O objetivo da normalização é alterar os valores das colunas numéricas do conjunto de dados para uma escala comum, sem modificar as diferenças nos intervalos de valores.<br>
Não precisamos aplicar normalização a todo conjunto de dados. É necessário apenas quando as colunas ou variáveis tiverem intervalos diferentes. Por exemplo, considere o conjunto de dados contendo duas variáveis, idade (x1) e salário (x2). Onde a faixa etária da idade varia de 20 a 100, enquanto o salário varia de 1000 a 20.000. O salário é até 200 vezes maior do que a idade e com uma variação de valores muito maior. Então, essas duas variáveis estão em escalas e em intervalos muito diferentes. Ao utilizar um algoritmo de Regressão Linear, por exemplo, o salário influenciará muito mais no resultado devido ao seu valor maior. E isso causa problemas durante o treinamento do algoritmo. <br>
A normalização também é chamada simplesmente de Scaler Min-Max e basicamente reduz o intervalo dos dados de forma que o intervalo seja fixo entre 0 e 1, ou -1 a 1, se houver valores negativos. <br>
Fórmula para normalizar os dados: <br><br>
$x_{novo} = \frac{x - x_{min}}{x_{max}-x_{min}}$ <br> <br>
Alguns algoritmos de Machine Learning que requerem a normalização dos dados são: <br>
1.KNN com medida de distância euclidiana se quiser que todos os recursos contribuam igualmente no modelo. <br>
2.Regressão Logística, SVM, Perceptrons, Redes Neurais. <br>
3.K-Means <br>
4.Análise discriminante linear, análise de componentes principais, análise de componentes principais do kernel.<br>
Classificadores baseados em modelos gráficos, como Fisher LDA ou  Naive  Bayes,  bem como Árvores de Decisão e métodos baseados em árvore, como  Random  Forest, são invariantes à normalização das variáveis. <br>
**É muito importante deixar claro que os valores não são alterados, apenas são colocados em uma escala entre 0 e 1.**
</details>

In [ ]:
# Carregando imagem dados originais x dados normalizados
from IPython.display import Image
Image('Imagens/dados-originais-dados normalizados.png')

In [1]:
# Importando os pacotes
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import Image
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [2]:
# Colettando os dados
df = pd.read_csv('Dados/Auto-mpg/mtcars.csv')
df

,model,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2
5,Valiant,18.1,6,225.0,105,2.76,3.460,20.22,1,0,3,1
6,Duster 360,14.3,8,360.0,245,3.21,3.570,15.84,0,0,3,4
7,Merc 240D,24.4,4,146.7,62,3.69,3.190,20.00,1,0,4,2
8,Merc 230,22.8,4,140.8,95,3.92,3.150,22.90,1,0,4,2
9,Merc 280,19.2,6,167.6,123,3.92,3.440,18.30,1,0,4,4
10,Merc 280C,17.8,6,167.6,123,3.92,3.440,18.90,1,0,4,4
11,Merc 450SE,16.4,8,275.8,180,3.07,4.070,17.40,0,0,3,3
12,Merc 450SL,17.3,8,275.8,180,3.07,3.730,17.60,0,0,3,3
13,Merc 450SLC,15.2,8,275.8,180,3.07,3.780,18.00,0,0,3,3
14,Cadillac Fleetwood,10.4,8,472.0,205,2.93,5.250,17.98,0,0,3,4
15,Lincoln Continental,10.4,8,460.0,215,3.00,5.424,17.82,0,0,3,4
16,Chrysler Imperial,14.7,8,440.0,230,3.23,5.345,17.42,0,0,3,4
17,Fiat 128,32.4,4,78.7,66,4.08,2.200,19.47,1,1,4,1
18,Honda Civic,30.4,4,75.7,52,4.93,1.615,18.52,1,1,4,2
19,Toyota Corolla,33.9,4,71.1,65,4.22,1.835,19.90,1,1,4,1
20,Toyota Corona,21.5,4,120.1,97,3.70,2.465,20.01,1,0,3,1
21,Dodge Challenger,15.5,8,318.0,150,2.76,3.520,16.87,0,0,3,2
22,AMC Javelin,15.2,8,304.0,150,3.15,3.435,17.30,0,0,3,2
23,Camaro Z28,13.3,8,350.0,245,3.73,3.840,15.41,0,0,3,4
24,Pontiac Firebird,19.2,8,400.0,175,3.08,3.845,17.05,0,0,3,2
25,Fiat X1-9,27.3,4,79.0,66,4.08,1.935,18.90,1,1,4,1
26,Porsche 914-2,26.0,4,120.3,91,4.43,2.140,16.70,0,1,5,2
27,Lotus Europa,30.4,4,95.1,113,3.77,1.513,16.90,1,1,5,2
28,Ford Pantera L,15.8,8,351.0,264,4.22,3.170,14.50,0,1,5,4
29,Ferrari Dino,19.7,6,145.0,175,3.62,2.770,15.50,0,1,5,6
30,Maserati Bora,15.0,8,301.0,335,3.54,3.570,14.60,0,1,5,8
31,Volvo 142E,21.4,4,121.0,109,4.11,2.780,18.60,1,1,4,2

In [4]:
# Retorna os valores do DataFrame e converte em uma matriz NumPy
valores = df[["mpg", "cyl", "disp", "hp", "drat", "wt", "qsec", "vs", "am", "gear", "carb"]].values

# Cria o objeto da classe MinMaxScaler
min_max_scaler = MinMaxScaler()

# Realiza a normalização dimensionando as variáveis em uma escala entre 0 e 1
dadosNormalizados = min_max_scaler.fit_transform(valores)
dadosNormalizados

array([[0.45106383, 0.5       , 0.22175106, 0.204947  , 0.52534562,
        0.28304781, 0.23333333, 0.        , 1.        , 0.5       ,
        0.42857143],
       [0.45106383, 0.5       , 0.22175106, 0.204947  , 0.52534562,
        0.34824853, 0.3       , 0.        , 1.        , 0.5       ,
        0.42857143],
       [0.52765957, 0.        , 0.0920429 , 0.14487633, 0.50230415,
        0.20634109, 0.48928571, 1.        , 1.        , 0.5       ,
        0.        ],
       [0.46808511, 0.5       , 0.46620105, 0.204947  , 0.14746544,
        0.43518282, 0.58809524, 1.        , 0.        , 0.        ,
        0.        ],
       [0.35319149, 1.        , 0.72062859, 0.43462898, 0.1797235 ,
        0.49271286, 0.3       , 0.        , 0.        , 0.        ,
        0.14285714],
       [0.32765957, 0.5       , 0.38388626, 0.18727915, 0.        ,
        0.49782664, 0.68095238, 1.        , 0.        , 0.        ,
        0.        ],
       [0.16595745, 1.        , 0.72062859, 0.6819788 , 0.20737327,
        0.52595244, 0.15952381, 0.        , 0.        , 0.        ,
        0.42857143],
       [0.59574468, 0.        , 0.1885757 , 0.03533569, 0.42857143,
        0.42879059, 0.6547619 , 1.        , 0.        , 0.5       ,
        0.14285714],
       [0.52765957, 0.        , 0.17385882, 0.15194346, 0.53456221,
        0.41856303, 1.        , 1.        , 0.        , 0.5       ,
        0.14285714],
       [0.37446809, 0.5       , 0.24070841, 0.25088339, 0.53456221,
        0.49271286, 0.45238095, 1.        , 0.        , 0.5       ,
        0.42857143],
       [0.31489362, 0.5       , 0.24070841, 0.25088339, 0.53456221,
        0.49271286, 0.52380952, 1.        , 0.        , 0.5       ,
        0.42857143],
       [0.25531915, 1.        , 0.51060115, 0.45229682, 0.14285714,
        0.65379698, 0.3452381 , 0.        , 0.        , 0.        ,
        0.28571429],
       [0.29361702, 1.        , 0.51060115, 0.45229682, 0.14285714,
        0.56686269, 0.36904762, 0.        , 0.        , 0.        ,
        0.28571429],
       [0.20425532, 1.        , 0.51060115, 0.45229682, 0.14285714,
        0.57964715, 0.41666667, 0.        , 0.        , 0.        ,
        0.28571429],
       [0.        , 1.        , 1.        , 0.54063604, 0.07834101,
        0.9555101 , 0.41428571, 0.        , 0.        , 0.        ,
        0.42857143],
       [0.        , 1.        , 0.97006735, 0.57597173, 0.11059908,
        1.        , 0.3952381 , 0.        , 0.        , 0.        ,
        0.42857143],
       [0.18297872, 1.        , 0.9201796 , 0.62897527, 0.21658986,
        0.97980056, 0.34761905, 0.        , 0.        , 0.        ,
        0.42857143],
       [0.93617021, 0.        , 0.01895735, 0.04946996, 0.60829493,
        0.1756584 , 0.59166667, 1.        , 1.        , 0.5       ,
        0.        ],
       [0.85106383, 0.        , 0.01147418, 0.        , 1.        ,
        0.02608029, 0.47857143, 1.        , 1.        , 0.5       ,
        0.14285714],
       [1.        , 0.        , 0.        , 0.0459364 , 0.67281106,
        0.08233188, 0.64285714, 1.        , 1.        , 0.5       ,
        0.        ],
       [0.47234043, 0.        , 0.12222499, 0.1590106 , 0.43317972,
        0.24341601, 0.65595238, 1.        , 0.        , 0.        ,
        0.        ],
       [0.21702128, 1.        , 0.61586431, 0.34628975, 0.        ,
        0.51316799, 0.28214286, 0.        , 0.        , 0.        ,
        0.14285714],
       [0.20425532, 1.        , 0.58094288, 0.34628975, 0.1797235 ,
        0.49143442, 0.33333333, 0.        , 0.        , 0.        ,
        0.14285714],
       [0.12340426, 1.        , 0.69568471, 0.6819788 , 0.44700461,
        0.59498849, 0.10833333, 0.        , 0.        , 0.        ,
        0.42857143],
       [0.37446809, 1.        , 0.82040409, 0.43462898, 0.14746544,
        0.59626694, 0.30357143, 0.        , 0.        , 0.        ,
        0.14285714],
       [0.71914894, 0.        , 0.01970566, 0.04946996, 0.60829493,
        0.10790079, 0.52380952, 1.        , 1.        , 0.5       ,
        0.        ],
       [0.66382979, 0.        , 0.12272387, 0.13780919, 0.76958525,
        0.16031705, 0.26190476, 0.        , 1.        , 1.        ,
        0.14285714],
       [0.85106383, 0.        , 0.0598653 , 0.2155477 , 0.46543779,
        0.        , 0.28571429, 1.        , 1.        , 1.        ,
        0.14285714],
       [0.22978723, 1.        , 0.6981791 , 0.74911661, 0.67281106,
        0.42367681, 0.        , 0.        , 1.        , 1.        ,
        0.42857143],
       [0.39574468, 0.5       , 0.18433525, 0.43462898, 0.39631336,
        0.32140118, 0.11904762, 0.        , 1.        , 1.        ,
        0.71428571],
       [0.19574468, 1.        , 0.57345972, 1.        , 0.359447  ,
        0.52595244, 0.01190476, 0.        , 1.        , 1.        ,
        1.        ],
       [0.46808511, 0.        , 0.12446994, 0.20141343, 0.62211982,
        0.32395807, 0.48809524, 1.        , 1.        , 0.5       ,
        0.14285714]])

In [ ]:
# Redimensiona os dados para o estado original.
min_max_scaler.inverse_transform(dadosNormalizados)

## Padronização
<details>
    <summary>
        <a class="btnfire small stroke"><em class="fas fa-chevron-circle-down"></em>&nbsp;&nbsp;Clique para mais detalhes</a>
    </summary>
    <br>

A padronização, também conhecida como normalização do escore Z, ou em inglês Standardization, ou ainda Standard Scaler é o processo de redimensionamento dos valores das variáveis para que eles tenham as propriedades de uma distribuição normal. Os dados em uma distribuição normal possuem média igual a zero e desvio padrão igual a 1. <br>
Os escores z das variáveis são calculadas da seguinte forma:<br><br>
$Z = \frac{X - μ}{σ}$ <br> <br>
Onde:<br>
x é o valor da variável;<br>
μ é a média;<br>
e σ é o desvio padrão.<br>
A padronização é amplamente utilizada com os algoritmos SVMs, regressão logística e redes neurais.

</details>

In [ ]:
# Carregando imagem dados originais x dados padronizados
Image('Imagens/dados-originais-versus-dados padronizados.png')

In [5]:
# Criando os  dados
dicionario = {
    "coluna1": [1., 2., 0.],
    "coluna2": [-1., 0., 1.],
    "coluna3": [2., 0., -1.]
}

df2 = pd.DataFrame(dicionario)
df2

   coluna1  coluna2  coluna3
0      1.0     -1.0      2.0
1      2.0      0.0      0.0
2      0.0      1.0     -1.0

In [ ]:
# Exibe um resumo estatístico dos dados
df2.describe()

In [6]:
# Retorna os valores do DataFrame e converte em uma matriz NumPy
valores = df2.values

# Cria o objeto StandardScaler
scaler = StandardScaler()

# Realiza a padronização centralizando e dimensionando dados.
valoresPadronizados = scaler.fit_transform(valores)
valoresPadronizados

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [7]:
# axis = 0 em NumPy refere-se à coluna
# Neste exemplo está retornando a média de todas as colunas
valoresPadronizados.mean(axis=0)

array([0., 0., 0.])

In [8]:
# axis = 0 em NumPy refere-se à coluna
# Neste exemplo está retornando o desvio padrão de todas as colunas
valoresPadronizados.std(axis=0)

array([1., 1., 1.])

In [ ]:
# Exibe o resumo estatístico dos dados
df.describe()

In [ ]:
# Retorna os valores do DataFrame e converte em uma matriz NumPy
valores = df[["mpg", "cyl", "disp", "hp", "drat", "wt", "qsec", "vs", "am", "gear", "carb"]].values

# Calcula a média e o desvio-padrão a serem usados para dimensionar os dados
scaler = StandardScaler().fit(valores)

# Realiza a padronização centralizando e dimensionando dados.
valoresPadronizados = scaler.transform(valores)

In [ ]:
# axis = 0 em NumPy refere-se à coluna
# Neste exemplo está retornando a média de todas as colunas
valoresPadronizados.mean(axis=0)

In [ ]:
# axis = 0 em NumPy refere-se à coluna
# Neste exemplo está retornando o desvio padrão de todas as colunas
valoresPadronizados.std(axis=0)

In [ ]:
# Retorna os dados para o estado original.
scaler.inverse_transform(valoresPadronizados)